# Enable the H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:bmidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# This keeps the database alive as long as the app is running
spring.jpa.defer-datasource-initialization=true